/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jml.eggexercises;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author jmlucero
 */
public class EjerciciosEgg extends javax.swing.JFrame {

    /**
     * Creates new form Console
     */
    String command;
    Graphics g;
    Exercise myExercise;
    Document doc;
    int drawPanelWidth;
    int drawPanelHeight;
    String title = " Aplicación de los Ejercicios de Java - Egg  || José Ma. Lucero ";
    
    public EjerciciosEgg() {
        
        initComponents();
        doc = jTextPane1.getStyledDocument();
        this.myExercise = new DefaultExercise(jTextPane1, jTextField1, doc);
        this.myExercise.AddTextToPane("Bienvenido a la app de ejercicios de Egg en Java...");
        Image image = Toolkit.getDefaultToolkit().getImage("src/image.png");
        ImageIcon icon = new ImageIcon(image);
        setIconImage(image);
        TimerTask tasknew = new TimerTask() {
            @Override
            public void run() {
                setTitle();
            }
        };
        Timer timer = new Timer(true);
        timer.scheduleAtFixedRate(tasknew, 0, 200);
        SimpleAttributeSet set = new SimpleAttributeSet();
        StyleConstants.setForeground(set, Color.red);
        this.jTextField1.setFocusable(true);
        this.jTextField1.grabFocus();
        
        this.jTextField1.addFocusListener(new FocusListener()  {
            public void actionPerformed(java.awt.event.FocusEvent evt) {
                System.out.println("EVENTO "+evt.toString());
            }

            @Override
            public void focusGained(FocusEvent e) {
                System.out.println("Cursor en la entrada de texto");
            }

            @Override
            public void focusLost(FocusEvent e) {
                System.out.println("Cursor fuera de la entrada de texto");
            }
        });
        
    }

    public void setTitle() {
        char letter;
        letter = title.charAt(0);
        title = title.substring(1).concat(String.valueOf(letter));
        this.setTitle(title);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        specialButton = new java.awt.Button();
        cleanButton1 = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        buttonEj15 = new java.awt.Button();
        buttonEj01 = new java.awt.Button();
        buttonEj21 = new java.awt.Button();
        buttonTest = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        buttonEx09 = new java.awt.Button();
        buttonEx10 = new java.awt.Button();
        buttonEx11 = new java.awt.Button();
        buttonEx23 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 0));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.setMargin(new java.awt.Insets(6, 6, 6, 6));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane1.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 12)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 246, 0));
        jTextPane1.setMargin(new java.awt.Insets(15, 15, 15, 15));
        jScrollPane1.setViewportView(jTextPane1);

        specialButton.setActionCommand("specialButtonAction");
        specialButton.setLabel("Ejecutar Acción");
        specialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialButtonActionPerformed(evt);
            }
        });

        cleanButton1.setActionCommand("Clean");
        cleanButton1.setLabel("Limpiar Pantalla");
        cleanButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("EJERCICIOS BASE"));

        buttonEj15.setActionCommand("Ej15");
        buttonEj15.setLabel("E 15");
        buttonEj15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEj15ActionPerformed(evt);
            }
        });

        buttonEj01.setActionCommand("Ej01");
        buttonEj01.setLabel("E 01");
        buttonEj01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEj01ActionPerformed(evt);
            }
        });

        buttonEj21.setActionCommand("Ej21");
        buttonEj21.setLabel("E 21");
        buttonEj21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEj21ActionPerformed(evt);
            }
        });

        buttonTest.setActionCommand("Test");
        buttonTest.setLabel("Tests");
        buttonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEj01, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEj15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEj21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTest, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(buttonEj01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEj15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEj21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(buttonTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("EXTRAS"));

        buttonEx09.setActionCommand("Ex09");
        buttonEx09.setLabel("Ex 09");
        buttonEx09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEx09ActionPerformed(evt);
            }
        });

        buttonEx10.setActionCommand("Ex10");
        buttonEx10.setLabel("Ex 10");
        buttonEx10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEx10ActionPerformed(evt);
            }
        });

        buttonEx11.setActionCommand("Ex11");
        buttonEx11.setLabel("Ex 11");
        buttonEx11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEx11ActionPerformed(evt);
            }
        });

        buttonEx23.setActionCommand("Ex23");
        buttonEx23.setLabel("Ex 23");
        buttonEx23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEx23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonEx09, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(buttonEx10, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(buttonEx11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEx23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(buttonEx09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(buttonEx10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEx11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(buttonEx23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(specialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cleanButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cleanButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(specialButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
//        System.out.println("Type of event: " + evt.toString());
//        command=evt.getActionCommand();
//        g.drawString(command, 100, 100);
//        jTextField1.setText("");
        

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buttonEj15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEj15ActionPerformed
        myExercise.removeListener();
        myExercise = new Ejercicio15(jTextPane1, jTextField1, doc);
    }//GEN-LAST:event_buttonEj15ActionPerformed

    private void specialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialButtonActionPerformed
        myExercise.buttonAction();
    }//GEN-LAST:event_specialButtonActionPerformed

    private void buttonEj01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEj01ActionPerformed
        myExercise.removeListener();
        myExercise = new Ejercicio1(jTextPane1, jTextField1, doc);
    }//GEN-LAST:event_buttonEj01ActionPerformed

    private void cleanButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButton1ActionPerformed
        jTextPane1.setText("");
    }//GEN-LAST:event_cleanButton1ActionPerformed

    private void buttonEj21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEj21ActionPerformed
        myExercise.removeListener();
        myExercise = new Ejercicio21(jTextPane1, jTextField1, doc);
    }//GEN-LAST:event_buttonEj21ActionPerformed

    private void buttonEx09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEx09ActionPerformed
        myExercise.removeListener();
        myExercise = new EjercicioEx09(jTextPane1, jTextField1, doc);
    }//GEN-LAST:event_buttonEx09ActionPerformed

    private void buttonEx10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEx10ActionPerformed
        myExercise.removeListener();
        myExercise = new EjercicioEx10(jTextPane1, jTextField1, doc);
    }//GEN-LAST:event_buttonEx10ActionPerformed

    private void buttonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTestActionPerformed
         myExercise.removeListener();
        myExercise = new Pruebas(jTextPane1, jTextField1, doc);
    }//GEN-LAST:event_buttonTestActionPerformed

    private void buttonEx11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEx11ActionPerformed
          myExercise.removeListener();
        myExercise = new EjercicioEx11(jTextPane1, jTextField1, doc);
    }//GEN-LAST:event_buttonEx11ActionPerformed

    private void buttonEx23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEx23ActionPerformed
        myExercise.removeListener();
        myExercise = new EjercicioEx23(jTextPane1, jTextField1, doc);
    }//GEN-LAST:event_buttonEx23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjerciciosEgg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjerciciosEgg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjerciciosEgg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjerciciosEgg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        // creating timer task, timer
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjerciciosEgg().setVisible(true);
                
            }
        });
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonEj01;
    private java.awt.Button buttonEj15;
    private java.awt.Button buttonEj21;
    private java.awt.Button buttonEx09;
    private java.awt.Button buttonEx10;
    private java.awt.Button buttonEx11;
    private java.awt.Button buttonEx23;
    private java.awt.Button buttonTest;
    private java.awt.Button cleanButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private java.awt.Button specialButton;
    // End of variables declaration//GEN-END:variables
}

class Task extends TimerTask {
    
    int count = 1;

    // run is a abstract method that defines task performed at scheduled time.
    public void run() {
        System.out.println(count + " : Mahendra Singh");
        count++;
    }
}
